### ISSUE TITLE
申请账号

### ISSUE THREAD

**Issue by leleZeng** [dustlight-cn/auth#11]
我正在学习如何开发出整套的用户中心授权中心，希望能申请可以查看所有功能权限的账号学习，谢谢！

**Comment by Hansin1997** [comment]
关于所有功能权限开放的账号的问题恐怕不能同意，非常抱歉。

## 推荐
建议本地部署项目，默认用户名和密码 ```root``` 和 ```123456```。

**Comment by leleZeng** [comment]
非常感谢
